import { Document, Page, Text, View, StyleSheet } from '@react-pdf/renderer';

const styles = StyleSheet.create({
  page: {
    padding: 30,
    backgroundColor: '#ffffff',
  },
  header: {
    backgroundColor: '#4F46E5',
    padding: 20,
    marginBottom: 20,
  },
  name: {
    fontSize: 28,
    fontWeight: 'bold',
    color: 'white',
    textAlign: 'center',
  },
  title: {
    fontSize: 16,
    color: '#E0E7FF',
    textAlign: 'center',
    marginTop: 5,
  },
  section: {
    marginBottom: 15,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#4F46E5',
    borderBottomWidth: 2,
    borderBottomColor: '#4F46E5',
    paddingBottom: 5,
    marginBottom: 10,
  },
  label: {
    fontSize: 12,
    color: '#6B7280',
    marginBottom: 2,
  },
  value: {
    fontSize: 14,
    color: '#1F2937',
    marginBottom: 8,
  },
  skillTag: {
    fontSize: 12,
    color: '#4F46E5',
    backgroundColor: '#EEF2FF',
    padding: 4,
    marginRight: 5,
    marginBottom: 5,
  },
  footer: {
    position: 'absolute',
    bottom: 30,
    left: 30,
    right: 30,
    textAlign: 'center',
    fontSize: 10,
    color: '#9CA3AF',
    borderTopWidth: 1,
    borderTopColor: '#E5E7EB',
    paddingTop: 10,
  },
});

export function CVPDF({ data }) {
  return (
    <Document>
      <Page size="A4" style={styles.page}>
        {/* Header */}
        <View style={styles.header}>
          <Text style={styles.name}>{data.fullName || 'Your Name'}</Text>
          <Text style={styles.title}>{data.jobTitle || 'Job Title'}</Text>
        </View>

        {/* Contact Info */}
        <View style={styles.section}>
          <Text style={styles.label}>📧 Email: {data.email || 'email@example.com'}</Text>
          <Text style={styles.label}>📱 Phone: {data.phone || '+92 300 0000000'}</Text>
          <Text style={styles.label}>📍 Address: {data.address || 'City, Country'}</Text>
        </View>

        {/* Summary */}
        <View style={styles.section}>
          <Text style={styles.sectionTitle}>📝 Professional Summary</Text>
          <Text style={styles.value}>{data.summary || 'Write your professional summary here...'}</Text>
        </View>

        {/* Experience */}
        <View style={styles.section}>
          <Text style={styles.sectionTitle}>💼 Work Experience</Text>
          {data.experience?.map((exp, index) => (
            <View key={index} style={{ marginBottom: 10 }}>
              <Text style={{ fontSize: 14, fontWeight: 'bold' }}>{exp.company}</Text>
              <Text style={{ fontSize: 12, color: '#6B7280' }}>
                {exp.role} | {exp.startDate} - {exp.endDate}
              </Text>
              <Text style={{ fontSize: 12, color: '#1F2937', marginTop: 3 }}>
                {exp.description}
              </Text>
            </View>
          ))}
        </View>

        {/* Education */}
        <View style={styles.section}>
          <Text style={styles.sectionTitle}>🎓 Education</Text>
          {data.education?.map((edu, index) => (
            <View key={index} style={{ marginBottom: 10 }}>
              <Text style={{ fontSize: 14, fontWeight: 'bold' }}>{edu.degree}</Text>
              <Text style={{ fontSize: 12, color: '#6B7280' }}>
                {edu.institute} | {edu.year}
              </Text>
            </View>
          ))}
        </View>

        {/* Skills */}
        <View style={styles.section}>
          <Text style={styles.sectionTitle}>🛠️ Skills</Text>
          <View style={{ flexDirection: 'row', flexWrap: 'wrap' }}>
            {data.skills?.map((skill, index) => (
              <Text key={index} style={styles.skillTag}>• {skill}</Text>
            ))}
          </View>
        </View>

        {/* Footer */}
        <Text style={styles.footer}>Generated by CV Builder • {new Date().getFullYear()}</Text>
      </Page>
    </Document>
  );
}